/**
 * Master topic queue for AI blog generation.
 * Topics are consumed in order — already-published slugs are skipped automatically.
 * Add new topics here to extend the queue.
 */

export const TOPIC_QUEUE = [
  // ── Tier 1: High commercial intent ────────────────────────────────────────
  {
    slug: 'vijaysar-wooden-glass-price',
    title: 'Vijaysar Wooden Glass Price in India: What to Expect in 2026',
    description: 'A clear guide to Vijaysar wooden glass prices in India — what affects cost, how to spot authentic wood, and where to buy at the best value.',
    primaryKeyword: 'vijaysar wooden glass price',
    angle: 'price guide and buying advice',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/product-pack_iyglnk',
    readTime: '5 min read',
  },
  {
    slug: 'vijaysar-glass-online-india',
    title: 'Buy Vijaysar Wooden Glass Online in India — A Buyer\'s Guide',
    description: 'Everything you need to know before buying a Vijaysar wooden glass online in India — authenticity checks, what size to pick, and delivery options.',
    primaryKeyword: 'buy vijaysar wooden glass online india',
    angle: 'buying guide with authenticity tips',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '6 min read',
  },
  {
    slug: 'vijaysar-glass-for-weight-loss',
    title: 'Vijaysar Glass and Weight Management: What Ayurveda Says',
    description: 'Exploring the traditional Ayurvedic perspective on Vijaysar wood and its role in supporting metabolic wellness and healthy weight management.',
    primaryKeyword: 'vijaysar glass weight loss',
    angle: 'Ayurvedic perspective on metabolism and Kapha balance',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '6 min read',
  },
  {
    slug: 'how-to-use-vijaysar-wooden-glass',
    title: 'How to Use a Vijaysar Wooden Glass: Step-by-Step Guide',
    description: 'A complete guide on how to use a Vijaysar wooden glass correctly — how long to soak, what water to use, morning routine, and how to care for the glass.',
    primaryKeyword: 'how to use vijaysar wooden glass',
    angle: 'detailed how-to with care instructions',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/how-to-use_lycjln',
    readTime: '5 min read',
  },
  {
    slug: 'vijaysar-glass-side-effects',
    title: 'Vijaysar Wooden Glass: Side Effects, Safety & Who Should Be Careful',
    description: 'An honest look at the safety of Vijaysar wooden glass — who can use it, any cautions to know, and what traditional Ayurvedic guidelines say.',
    primaryKeyword: 'vijaysar glass side effects',
    angle: 'safety-first, honest, no scaremongering — address concerns directly',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '5 min read',
  },
  {
    slug: 'vijaysar-glass-vs-copper-glass',
    title: 'Vijaysar Glass vs Copper Glass: Which Is Better for Your Morning Ritual?',
    description: 'A balanced comparison of Vijaysar wooden glass and copper glass — Ayurvedic traditions, differences in use, care, and who should use which.',
    primaryKeyword: 'vijaysar glass vs copper glass',
    angle: 'detailed comparison, balanced, not dismissive of copper',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/specs_slhudw',
    readTime: '6 min read',
  },
  {
    slug: 'pterocarpus-marsupium-benefits',
    title: 'Pterocarpus Marsupium (Vijaysar): Traditional Uses & Botanical Profile',
    description: 'A deep dive into Pterocarpus marsupium — the botanical name for the Vijaysar tree — its phytochemical profile, traditional uses in Ayurveda, and where it grows.',
    primaryKeyword: 'pterocarpus marsupium benefits',
    angle: 'educational and botanical, cite classical texts',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '7 min read',
  },

  // ── Tier 2: Informational / lifestyle ─────────────────────────────────────
  {
    slug: 'ayurvedic-morning-routine',
    title: 'The Ayurvedic Morning Routine: 7 Rituals to Start Your Day Right',
    description: 'Discover the traditional Ayurvedic morning routine — from Ushapan (dawn drinking) and oil pulling to yoga and the role of the Vijaysar glass.',
    primaryKeyword: 'ayurvedic morning routine',
    angle: 'lifestyle, include Vijaysar glass as one of the 7 rituals',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '7 min read',
  },
  {
    slug: 'vijaysar-wood-tree-india',
    title: 'The Vijaysar Tree: India\'s Ancient Healing Wood Explained',
    description: 'Learn about the Vijaysar tree — where it grows in India, why Ayurveda has used it for 2,000 years, and what makes its heartwood so special.',
    primaryKeyword: 'vijaysar tree india',
    angle: 'educational origin story, geography, ecology',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '6 min read',
  },
  {
    slug: 'blood-sugar-management-ayurveda',
    title: 'Blood Sugar Management the Ayurvedic Way: Traditional Practices Explained',
    description: 'Explore how Ayurveda approaches blood sugar and metabolic wellness — from Prameha classification to dietary guidelines, herbs, and daily rituals.',
    primaryKeyword: 'blood sugar management ayurveda',
    angle: 'educational overview of Ayurvedic approach to Prameha',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '8 min read',
  },
  {
    slug: 'ushapan-morning-water-benefits',
    title: 'Ushapan: The Ayurvedic Practice of Drinking Water First Thing in the Morning',
    description: 'What is Ushapan? Discover the ancient Ayurvedic practice of drinking water at dawn — its origins, how to do it, and why the Vijaysar glass makes it meaningful.',
    primaryKeyword: 'ushapan benefits ayurveda',
    angle: 'cultural/spiritual angle on the morning water ritual',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/how-to-use_lycjln',
    readTime: '5 min read',
  },
  {
    slug: 'best-ayurvedic-products-blood-sugar',
    title: '7 Traditional Ayurvedic Products for Blood Sugar Wellness',
    description: 'A roundup of the most commonly used traditional Ayurvedic products for supporting blood sugar wellness — including Vijaysar, Karela, Methi, and more.',
    primaryKeyword: 'ayurvedic products for blood sugar',
    angle: 'listicle with balanced overview, Vijaysar as number 1',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/benefits_fnxzdh',
    readTime: '7 min read',
  },
  {
    slug: 'vijaysar-water-colour-change',
    title: 'Why Does Vijaysar Glass Water Turn Pink? (And What It Means)',
    description: 'The water in your Vijaysar glass turns pink or brown overnight — here\'s exactly why it happens, what the colour tells you about the wood, and when to be concerned.',
    primaryKeyword: 'vijaysar glass water colour change',
    angle: 'FAQ-style, science-lite, reassuring',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '4 min read',
  },
  {
    slug: 'vijaysar-glass-care-guide',
    title: 'How to Care for Your Vijaysar Wooden Glass: Complete Maintenance Guide',
    description: 'Keep your Vijaysar glass lasting for years — a complete care guide covering cleaning, drying, storage, what to avoid, and when to replace.',
    primaryKeyword: 'vijaysar glass care',
    angle: 'practical maintenance guide',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/how-to-use_lycjln',
    readTime: '5 min read',
  },
  {
    slug: 'ayurvedic-gifts-for-parents',
    title: 'Best Ayurvedic Gifts for Parents: Thoughtful & Healthy Choices',
    description: 'Looking for a meaningful health gift for your parents or elders? Explore the best Ayurvedic gift ideas rooted in Indian tradition — starting with the Vijaysar glass.',
    primaryKeyword: 'ayurvedic gifts for parents india',
    angle: 'gifting guide, emotional tone, family wellness',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/product-pack_iyglnk',
    readTime: '6 min read',
  },
  {
    slug: 'prameha-ayurveda-diabetes',
    title: 'Prameha in Ayurveda: The Ancient Classification of Metabolic Disorders',
    description: 'What is Prameha? How did ancient Ayurvedic physicians understand and classify metabolic and urinary disorders — and what does it mean for modern wellness?',
    primaryKeyword: 'prameha ayurveda',
    angle: 'educational deep dive into classical Ayurvedic texts',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '7 min read',
  },

  // ── Tier 3: Hindi/Hinglish ─────────────────────────────────────────────────
  {
    slug: 'vijaysar-glass-ke-fayde',
    title: 'Vijaysar Glass Ke Fayde: Ayurvedic Parampara Aur Upyog',
    description: 'Vijaysar wooden glass ke pramukhfayde — Ayurvedic parampara, sahi tarike se upyog, aur isse kya umeed rakhein. Ek saral aur ईमानदार guide.',
    primaryKeyword: 'vijaysar glass ke fayde',
    angle: 'Hindi language article, same tone as English posts, clear disclaimer',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/benefits_fnxzdh',
    readTime: '5 min read',
  },
  {
    slug: 'vijaysar-glass-for-thyroid',
    title: 'Vijaysar Glass and Thyroid Wellness: What Ayurvedic Tradition Says',
    description: 'Can Vijaysar glass support thyroid health? An honest look at what Ayurvedic tradition says, what to realistically expect, and important cautions.',
    primaryKeyword: 'vijaysar glass thyroid',
    angle: 'balanced, honest, strong disclaimer — thyroid is sensitive topic',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '6 min read',
  },
  {
    slug: 'vijaysar-glass-90-day-experience',
    title: '90 Days with a Vijaysar Wooden Glass: What to Expect Week by Week',
    description: 'A realistic guide to what the traditional 90-day Vijaysar glass ritual looks like — what you might notice, how to stay consistent, and the full cycle explained.',
    primaryKeyword: 'vijaysar glass 90 days',
    angle: 'journey narrative, week by week, managing expectations honestly',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '6 min read',
  },
  {
    slug: 'authentic-vijaysar-wood-how-to-identify',
    title: 'How to Identify Authentic Vijaysar Wood: 5 Signs You Should Know',
    description: 'With fake products flooding the market, here is how to identify genuine Vijaysar (Pterocarpus marsupium) heartwood — colour, smell, water test, and more.',
    primaryKeyword: 'authentic vijaysar wood identify',
    angle: 'buyer protection, empowering, reference Vedayu as trusted source at end',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '5 min read',
  },
  {
    slug: 'kapha-pitta-dosha-ayurveda',
    title: 'Kapha and Pitta Dosha: Understanding Your Metabolic Type in Ayurveda',
    description: 'An accessible guide to Kapha and Pitta doshas in Ayurveda — how they affect metabolism, which foods and habits help, and how Vijaysar wood fits in.',
    primaryKeyword: 'kapha pitta dosha ayurveda',
    angle: 'educational dosha guide, tie to Vijaysar wood at end naturally',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '7 min read',
  },

  // ── Tier 4: Condition & compound keyword gaps ──────────────────────────────
  {
    slug: 'vijaysar-for-cholesterol',
    title: 'Vijaysar Wood and Cholesterol: What Ayurvedic Tradition Says',
    description: 'Can Vijaysar wood support healthy cholesterol levels? Explore the traditional Ayurvedic perspective on fat metabolism, Kapha balance, and the role of Vijaysar in a wellness routine.',
    primaryKeyword: 'vijaysar for cholesterol',
    angle: 'balanced, honest, strong disclaimer — frame as metabolic wellness not cholesterol drug',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/benefits_fnxzdh',
    readTime: '6 min read',
  },
  {
    slug: 'vijaysar-for-liver-health',
    title: 'Vijaysar Wood for Liver Health: Traditional Ayurvedic Perspective',
    description: 'Discover how Ayurvedic tradition has used Vijaysar (Pterocarpus marsupium) for liver and digestive wellness — its Tikta Rasa properties, hepatoprotective associations, and honest expectations.',
    primaryKeyword: 'vijaysar for liver health',
    angle: 'educational, cite classical Ayurvedic hepatoprotective herbs, honest about limits',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '6 min read',
  },
  {
    slug: 'vijaysar-for-skin-and-hair',
    title: 'Vijaysar Wood for Skin and Hair: Traditional Ayurvedic Uses',
    description: 'Explore traditional Ayurvedic uses of Vijaysar (Pterocarpus marsupium) for skin disorders, hair growth, and blood purification — what classical texts say and realistic expectations.',
    primaryKeyword: 'vijaysar for skin disorders hair growth',
    angle: 'cover both skin and hair in one comprehensive post, tie to blood purification tradition',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '6 min read',
  },
  {
    slug: 'vijaysar-for-anemia-blood-health',
    title: 'Vijaysar Wood and Blood Health: Ayurvedic Tradition on Anemia and Purification',
    description: 'Traditional Ayurveda associates Vijaysar with blood purification (Raktashodhana). What does classical practice say about Vijaysar for anemia and overall blood health?',
    primaryKeyword: 'vijaysar for anemia',
    angle: 'educational, blood purification Ayurvedic concept, strong disclaimer about iron-deficiency anemia',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '5 min read',
  },
  {
    slug: 'vijaysar-for-dental-care',
    title: 'Vijaysar Wood for Dental Care: Ayurvedic Oral Wellness Traditions',
    description: 'How did Ayurveda use Vijaysar wood for oral health and dental care? Explore the astringent and antibacterial properties of Pterocarpus marsupium in traditional oral hygiene practices.',
    primaryKeyword: 'vijaysar for dental care',
    angle: 'tie to oral wellness tradition, mention Miswak as a companion natural dental practice',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/lifestyle_ehmoyv',
    readTime: '5 min read',
  },
  {
    slug: 'vijaysar-digestive-health-intestinal-worms',
    title: 'Vijaysar and Digestive Wellness: Ayurveda on Gut Health and Anthelmintic Herbs',
    description: 'Traditional Ayurveda classifies Vijaysar among herbs used for digestive wellness and intestinal health. Explore what classical texts say about anthelmintic herbs and healthy digestion.',
    primaryKeyword: 'vijaysar for digestive health intestinal worms',
    angle: 'educational overview of Ayurvedic anthelmintic tradition, Vijaysar role in digestive wellness',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/benefits_fnxzdh',
    readTime: '6 min read',
  },
  {
    slug: 'epicatechin-pterostilbene-vijaysar',
    title: 'Epicatechin, Pterostilbene & Marsupsin: The Active Compounds in Vijaysar Wood',
    description: 'A deep dive into the bioactive compounds in Vijaysar (Pterocarpus marsupium) — epicatechin, pterostilbene, marsupsin, and kino-tannins — and what traditional Ayurveda and modern research say.',
    primaryKeyword: 'epicatechin pterostilbene vijaysar marsupsin',
    angle: 'science-forward but balanced — explain the compounds, reference Ayurvedic classification too',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/authentic_k9fg3q',
    readTime: '7 min read',
  },
  {
    slug: 'vijaysar-glass-vs-churna-vs-capsules',
    title: 'Vijaysar Glass vs Churna vs Capsules: Which Form Is Best?',
    description: 'A clear comparison of the different forms of Vijaysar available — wooden glass, bark powder (churna), capsules, and extract — which is most authentic, easiest to use, and why the traditional glass wins.',
    primaryKeyword: 'vijaysar churna capsules glass comparison',
    angle: 'honest comparison, position the glass as most traditional and authentic',
    image: 'https://res.cloudinary.com/ddmmfkvwb/image/upload/q_auto,f_auto/product-pack_iyglnk',
    readTime: '6 min read',
  },
];
